# permissions for end users to view nodeops.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodeop-viewer-role
rules:
- apiGroups:
  - nodes.jike.com
  resources:
  - nodeops
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nodes.jike.com
  resources:
  - nodeops/status
  verbs:
  - get
