
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - nodes.jike.com
  resources:
  - nodeops
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nodes.jike.com
  resources:
  - nodeops/status
  verbs:
  - get
  - patch
  - update
